ProyectoFlex/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView


from toolcrib import urls

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/toolcrib/'), name='index'),# Index Redirect
    url(r'^admin/', admin.site.urls),
    url(r'^toolcrib/', include(urls, namespace='toolcrib'))
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

toolcrib/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views


urlpatterns = [
    
    # Auth Urls
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/toolcrib/login/'}, name='logout'),

    # App views    
   	url(r'^$', views.principal, name='principal'),
   	url(r'^ordersmanager/$', views.ordersmanager, name='ordersmanager'),
 	url(r'^orderssupervisor/$', views.orderssupervisor, name='orderssupervisor'),  
 	url(r'^updateproduct/$', views.updateproduct, name='updateproduct'),	
 	url(r'^updateuser/$', views.updateuser, name='updateuser'),
 	url(r'^parts/$', views.parts, name='parts'),
 	url(r'^shopingcart/$', views.shopingcart, name='shopingcart'),
 	url(r'^ordersmanagercart/(?P<pk>[0-9]+)/$', views.ordersmanagercart, name='ordersmanagercart'),
 	url(r'^orderssupervisorcart/(?P<pk>[0-9]+)/$', views.orderssupervisorcart, name='orderssupervisorcart'),
 	url(r'^orderCanceled/(?P<pk>[0-9]+)/$', views.orderCanceled, name='orderCanceled'),
 	url(r'^deleteCart/$', views.deleteCart, name='deleteCart'),
 	url(r'^showorders/$', views.showorders, name='showorders'),
 	url(r'^update-order-status-email/(?P<token>[\w.:\-_=]+)/$', views.update_order_status_by_email, name='update_order_status_by_email'),
 	
]

toolcrib/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from os import path

from django.db import models
from django.contrib.auth.models import User



def unique_file_path(instance, filename):	
    base, ext = path.splitext(filename)
    newname = "%s%s" % (instance.num_part, ext)
    return path.join('parts_img', newname)


# Create your models here.
class Part(models.Model):
	num_part = models.CharField(max_length=70, unique=True, null=False, blank=False)
	description = models.CharField(max_length=100, db_index=True, null=False, blank=False)
	inventory_type = models.CharField(max_length=100, db_index=True)
	image = models.ImageField(upload_to=unique_file_path, null=True, blank=False)	
	category = models.CharField(
		max_length=1, blank=False, default='1', choices=(
			('1','SUPPLY'),
			('2','SPARE PARTS')
		)
	)
	clas = models.CharField(
		max_length = 1, blank=False, default='1', choices =(
			('1','MXN'),
			('2','USD')
		)
	)
	location = models.CharField(max_length=200, null=True, blank=True)
	price = models.DecimalField(max_digits=10, decimal_places=2, null=False, blank=False)
	quantity = models.PositiveIntegerField(null=False, blank=False)
	max_quantity = models.PositiveIntegerField(null=False, blank=False)
	min_quantity = models.PositiveIntegerField(null=False, blank=False)

	def __str__(self):
		return self.num_part


class Order(models.Model):	
	status = models.CharField(
		max_length = 1, blank=False, default='1', choices =(
			('1','Pennding'),
			('2','Approved'),
			('3','Canceled'),
			('4','Done'),
		)
	)
	level = models.CharField(
		max_length = 1, blank=False, default='1', choices =(
			('1','Low'),
			('2','Medium'),
			('3','High'),
		)
	)
	
	cost_center = models.CharField(max_length=100, null=False, blank=False)
	comments = models.CharField(max_length=200, null=True, blank=True)
	
	user = models.ForeignKey(
		User, null=False, blank=False, related_name='order_set', on_delete=models.PROTECT
	)
	supervisor = models.ForeignKey(
		User, null=False, blank=False, related_name='superviced_order_set', on_delete=models.PROTECT
	)
		
	date_order = models.DateTimeField(null=False, blank=False, auto_now_add=True)
	date_approved = models.DateTimeField(null=True, blank=True)
	date_done = models.DateTimeField(null=True, blank=True)

	def __str__(self):
		return 'Order N: {0} Status: {1}'.format(self.id, self.get_status_display())


class OrderDetail(models.Model):
	order = models.ForeignKey(Order, null=False, blank=False, related_name='order_detail_set', on_delete=models.CASCADE)
	part = models.ForeignKey(Part, null=False, blank=False, related_name='part_detail_set', on_delete=models.PROTECT)
	quantity = models.PositiveIntegerField(null=False, blank=False)
	
	def __str__(self):
		return 'Part N. {0} Cant: {1}'.format(self.part.num_part, self.quantity)

toolcrib/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from django.contrib.auth.models import User

from .models import Part


class PartForm(forms.Form):
	num_part = forms.CharField(max_length=70, required=True, strip=True)
	
	category = forms.ChoiceField(
		required=True, choices=(
			('1','SUPPLY'),
			('2','SPARE PARTS')
		)
	)

	image = forms.ImageField(required=True)


class UserForm(forms.Form):
	username = forms.CharField(max_length=191, required=True, strip=True)
	email = forms.CharField(max_length=191, required=True, strip=True)
	password = forms.CharField(max_length=191, required=True, strip=True)
	group = forms.ChoiceField(
		required=True, choices=(
			('Manager','Manager'),
			('Supervisor','Supervisor'),
			('Technical','Technical'),
			('Production','Production')
		)
	)

toolcrib/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import urllib

from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse #email sender
from django.template import Context #email sender
from django.template.loader import render_to_string, get_template #email sender
from django.core.mail import EmailMessage, EmailMultiAlternatives #email sender
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User, Group
from django.conf import settings
from django.core import signing

from datetime import datetime
from .models import Part, Order, OrderDetail
from .forms import PartForm, UserForm

# Create your views here.
@login_required()
def principal(request):
	return render(request, 'principal.html')


@login_required()
@permission_required('toolcrib.add_part')
def ordersmanager(request):	
	# Order.status (2=approved)
	orders = Order.objects.filter(status='2').order_by('level').reverse()
	return render(request, 'ordersmanager.html', {'orders':orders})


@login_required()
@permission_required('toolcrib.change_order')
def orderssupervisor(request):
	# Order.status (1=Pennding)
	orders = Order.objects.filter(status='1', supervisor=request.user).order_by('level').reverse()
	return render(request, 'orderssupervisor.html', {'orders':orders})


@login_required()
@permission_required('toolcrib.add_part')
def updateproduct(request):
	if request.method == 'POST':
		part = get_object_or_404(Part, num_part=request.POST.get('num_part'))
		form = PartForm(request.POST, request.FILES)
		if form.is_valid():
			part.category = form.cleaned_data['category']
			part.image = form.cleaned_data['image']
			part.save()
			response = redirect('toolcrib:updateproduct')
			toast_text = 'Tool {0} update successful'.format(part.num_part) 
			response['Location'] += '?%s' % urllib.urlencode({'toast': toast_text})
			return response
	else:
		form = PartForm()
	return render(request, 'updateproduct.html', {'form': form})


@login_required()
@permission_required('toolcrib.add_part')
def updateuser(request):
	if request.method == 'POST':
		user = get_object_or_404(User, username=request.POST.get('username'))
		form = UserForm(request.POST)
		if form.is_valid():			
			group = Group.objects.get(name=form.cleaned_data['group'])
			user.email = form.cleaned_data['email']
			user.set_password(form.cleaned_data['password'])
			user.groups.clear()#Remove user from previous grups
			user.groups.add(group)#Add user to form group
			user.save()
			toast_text = 'User {0} update successful'.format(user.username) 
			response = redirect('toolcrib:ordersmanager')
			response['Location'] += '?%s' % urllib.urlencode({'toast': toast_text})
			return response
	else:
		form = UserForm()
	return render(request, 'updateuser.html',{'form':form})


@login_required()
def parts(request):
	if request.method == "POST":
		id_part = request.POST.get('id_part', None)
		cant = request.POST.get('cant', None)
		tool = Part.objects.get(id=id_part)

		if int(cant) >= tool.quantity:
			toast_text = 'Part {0} can not be assortment.'.format(tool.description) 
			response = redirect('toolcrib:parts')
			response['Location'] += '?%s' % urllib.urlencode({'toast': toast_text})
			return response
			
		else:
			if 'cart' not in request.session:
				request.session['cart'] = [{'id_part': id_part, 'cant': cant}]
			else:
				cart = request.session['cart']
				cart.append({'id_part': id_part, 'cant': cant})
				request.session['cart'] = cart
			
			return redirect('toolcrib:parts')

	q = request.GET.get('q', None)
	page = request.GET.get('page', 1)
	category = request.GET.get('category', None)	
		
	#parts_list = Part.objects.filter(quantity__gt = 0)
	parts_list = Part.objects.all()

	if category != None and category != '0':
		parts_list = parts_list.filter(inventory_type=category)
	else:
		category = '0'

	if q != None and q != '':
		parts_list = parts_list.filter(description__icontains=q.strip()) | parts_list.filter(num_part__icontains=q.strip())
	else:
		q = ''

	paginator = Paginator(parts_list, 9)
	parts = paginator.page(page)
		
	return render(request, 'parts.html', {'parts' : parts, 'category': category, 'q':q})	


@login_required()
def shopingcart(request):
	if request.method == "GET":
		supervisors = User.objects.filter(groups__name='Supervisor')
		cart_v = []		
		if 'cart' not in request.session:
			request.session['cart'] = []
		for item in request.session['cart']:
			p = Part.objects.get(id=item['id_part'])
			cart_v.append(
				{'cant': item['cant'], 'part': p}
			)
		return render(request, 'shopingcart.html', {'cart':cart_v, 'supervisors':supervisors})	
	
	elif request.method == "POST":
		supervisor = request.POST.get('supervisor', None)
		level = request.POST.get('level', None)
		cost_center = request.POST.get('cost_center', None)

		o = Order()
		o.level = level
		o.cost_center = cost_center
		o.supervisor = User(id=supervisor)
		o.user = request.user
		o.save()

		for item in request.session['cart']:
			o.order_detail_set.create(
				part=Part(id=item['id_part']),
				quantity=item['cant']
			)

		del request.session['cart']

		# Create Order status update Token
		token = signing.dumps({'order_id': o.id, 'order_status': 2}) # Order status 2 is approved


		supervisor_email = User.objects.get(id=supervisor)
		print(supervisor_email)
		subject = 'ToolCrib: New order #{0} created by {1}'.format(o.id, o.user.get_full_name())
		html_content = get_template('emails/order_created.html').render({'order': o, 'token': token})

		msg = EmailMessage(
			subject=subject,
			body=html_content,
			from_email=settings.DEFAULT_FROM_EMAIL,
			to=[supervisor_email.email],
		)
		msg.content_subtype = "html"
		msg.send(fail_silently= not settings.DEBUG)

		toast_text = 'Order {0} done successful'.format(o.id) 
		response = redirect('toolcrib:parts')
		response['Location'] += '?%s' % urllib.urlencode({'toast': toast_text})
		return response


@login_required()
@permission_required('toolcrib.add_part')
def ordersmanagercart(request, pk):
	# Order.status (4=Done)
	order = get_object_or_404(Order, pk=pk)
	if request.method == "POST":
		comments = request.POST.get('comments', None)
		order.status = '4'
		order.comments = comments
		order.date_done = datetime.now()
		order.save()
		toast_text = 'Order {0} Done successful'.format(order.id) 
		response = redirect('toolcrib:ordersmanager')
		response['Location'] += '?%s' % urllib.urlencode({'toast': toast_text})

		subject = 'ToolCrib: order #{0} Done lets go to toolcrib'.format(order.id)
		html_content = get_template('emails/OrderDone.html').render({'order': order})

		msg = EmailMessage(
			subject=subject,
			body=html_content,
			from_email=settings.DEFAULT_FROM_EMAIL,
			to=[order.user.email,],
			cc=[order.supervisor.email,],
		)
		msg.content_subtype = "html"
		msg.send(fail_silently= not settings.DEBUG)

		return response

	return render(request, 'ordersmanagercart.html', {'order': order})


@login_required()
@permission_required('toolcrib.change_order')
def orderssupervisorcart(request, pk):	
	order = get_object_or_404(Order, pk=pk)
	if request.method == "POST":
		level = request.POST.get('level', None)
		comments = request.POST.get('comments', None)
		order.level = level
		order.status = '2'
		order.comments = comments
		order.date_approved = datetime.now()
		order.save()
		toast_text = 'Order {0} approved successful'.format(order.id) 
		response = redirect('toolcrib:orderssupervisor')
		response['Location'] += '?%s' % urllib.urlencode({'toast': toast_text})
		
		subject = 'ToolCrib: order #{0} approved by {1}'.format(order.id, order.supervisor)
		html_content = get_template('emails/OrderApproved.html').render({'order': order})

		msg = EmailMessage(
			subject=subject,
			body=html_content,
			from_email=settings.DEFAULT_FROM_EMAIL,
			to=['tool.crib.flex@gmail.com',],
			cc=[order.user.email, order.supervisor.email,],
		)
		msg.content_subtype = "html"
		msg.send(fail_silently= not settings.DEBUG)

		return response

	return render(request, 'orderssupervisorcart.html', {'order': order})


@login_required()
@permission_required('toolcrib.change_order')
def orderCanceled(request, pk):
	# Order.status (3=Cancel)
	order = get_object_or_404(Order, pk=pk)
	if request.method == "POST":
		comments = request.POST.get('comments', None)
		order.comments = comments
		order.status = '3'
		order.date_approved = datetime.now()
		order.save()
		
		subject = 'ToolCrib: Order #{0} was Canceled'.format(order.id)
		html_content = get_template('emails/OrderCancel.html').render({'order': order})

		msg = EmailMessage(
			subject=subject,
			body=html_content,
			from_email=settings.DEFAULT_FROM_EMAIL,
			to=[order.user.email,],
			cc=[order.supervisor.email,],
		)
		msg.content_subtype = "html"
		msg.send(fail_silently= not settings.DEBUG)

		return redirect('toolcrib:orderssupervisor')
	return render(request, 'orderCanceled.html', {'order':order})


@login_required()
def deleteCart(request):
	if request.method == "POST":
		del request.session['cart']
		return redirect('toolcrib:parts')
	return render(request, 'deleteCart.html')


@login_required()
def showorders(request):
	orders = Order.objects.all().order_by('status')
	return render(request,'showorders.html',{'orders':orders})


def update_order_status_by_email(request, token):
	data = signing.loads(token, max_age=60 * 60 * 48)# max_age = 2 days

	order_id = data['order_id']
	order_status = data['order_status']

	order = Order.objects.get(id=order_id)

	order.status = order_status
	order.save()

	return render(request, 'update_order_status_by_email.html', {'order':order })

toolcrib/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>ToolCrib</title>

	<!-- Google font -->
	<link href="//fonts.googleapis.com/css?family=Hind:400,700" rel="stylesheet" />

	<!-- Bootstrap -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />

	<!-- Slick -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/slick.css' %}" />
	<link type="text/css" rel="stylesheet" href="{% static 'css/slick-theme.css' %}" />

	<!-- nouislider -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/nouislider.min.css' %}" />

	<!-- Font Awesome Icon -->
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />

	<!-- toastr -->
	<link rel="stylesheet" href="{% static 'css/toastr.min.css' %}" />	

	<!-- Custom stlylesheet -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}" />	

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>	

<body>
	<!-- HEADER -->
	<header>
		<!-- top Header -->
		<div id="top-header">
			<div class="container">
				<div class="pull-left">
					<span>Welcome to ToolCrib!</span>
				</div>
				<div class="pull-right">
					<ul class="header-top-links">
						<li><a class="fa fa-list-ul" href="{% url 'toolcrib:parts' %}"> Parts</a></li>
						{% if user.groups.last.name == 'Supervisor' %}
							<li><a class="fa fa-tasks" href="{% url 'toolcrib:orderssupervisor'%}"> Orders</a></li>
						{% elif user.groups.last.name == 'Manager'  %}
							<li><a class="fa fa-tasks" href="{% url 'toolcrib:ordersmanager' %}"> Orders</a></li>
							<li><a class="fa fa-users" href="{% url 'toolcrib:updateuser' %}"> Update User</a></li>
							<li><a class="fa fa-gears" href="{% url 'toolcrib:updateproduct' %}"> Update Tool</a></li>
						{% endif %}
						<li><a class="fa fa-bar-chart" href="{% url 'toolcrib:showorders' %}"> Orders Panel</a></li>
					</ul>
				</div>
			</div>
		</div>
		<!-- /top Header -->

		<!-- header -->
		<div id="header">
			<div class="container">
				<div class="pull-left">
					<!-- Logo -->
					<div class="header-logo">
						<a class="logo" href="{% url 'toolcrib:principal' %}">
							<img src="{% static 'img/Flex_logo15_opt.png' %}" alt="">
						</a>
					</div>
					<!-- /Logo -->

					<!-- Search -->
					<div class="header-search">
						<form method="get" action="{% url 'toolcrib:parts' %}">							
							<input class="input search-input" type="text" name="q" placeholder="Enter your keyword">
							<select class="input search-categories" name="category">
								<optgroup>
									<option value="0">All Categories</option>
								</optgroup>
								<optgroup label="Supply">
									<option value="Adhesive">Adhesive</option>
								    <option value="Hand tools">Hand Tools</option>
								    <option value="Markers">Markers</option>								 
								</optgroup>
								<optgroup label="Spare Parts">
								    <option value="engines">Engines</option>
								    <option value="Machinery Components">Machinery Components</option>
								</optgroup>
							</select>
							<button type="submit" class="search-btn"><i class="fa fa-search"></i></button>
						</form>
					</div>
					<!-- /Search -->
				</div>
				<div class="pull-right">
					<ul class="header-btns">
						<!-- Account -->
						<li class="header-account dropdown default-dropdown">
							<div>
								<div class="header-btns-icon">
									<i class="fa fa-user-o"></i>
								</div>
								<strong class="text-uppercase">{{ user.first_name }}</strong>
								<small>{{ user.groups.last.name }} </small>
							</div>							
							<a href="{% url 'toolcrib:logout' %}" class="text-uppercase">Log Out</a>		
						</li>
						<!-- /Account -->

						<!-- Cart -->
						<li class="header-cart dropdown default-dropdown">
							<div>
								<div class="header-btns-icon">
									<i class="fa fa-shopping-cart"></i>
									<span class="qty">{{ request.session.cart | length }}</span>
								</div>
								<strong class="text-uppercase">My Cart:</strong>
							</div>
							<a href="{% url 'toolcrib:shopingcart' %}">My Order</a>
						</li>						
						<!-- /Cart -->
					</ul>
				</div>
			</div>
			<!-- header -->
		</div>
		<!-- container -->
	</header>
	<!-- /HEADER -->	

	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container-fluid">			
			{% block 'main' %}
			{% endblock %}				
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->

	<!-- FOOTER -->
	<footer id="footer" class="section section-grey">
		<!-- container -->
		<div class="container">			
			<hr>
			<!-- row -->
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center">
					<!-- footer copyright -->
					<div class="footer-copyright">
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This Web application was made <i class="fa fa-user" aria-hidden="true"></i> by <a>Carlos Iturrios</a>
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
					</div>
					<!-- /footer copyright -->
				</div>
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</footer>
	<!-- /FOOTER -->

	<!-- jQuery Plugins -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/slick.min.js' %}"></script>
	<script src="{% static 'js/nouislider.min.js' %}"></script>
	<script src="{% static 'js/jquery.zoom.min.js' %}"></script>
	<script src="{% static 'js/toastr.min.js' %}"></script>	
	<script src="{% static 'js/main.js' %}"></script>
	<script type="text/javascript">
		{% if request.GET.toast %}
			toastr.options.closeButton = true;
			toastr.options.progressBar = true;
			toastr.info("{{request.GET.toast}}")
		{% endif %}		
	</script>

</body>

</html>

toolcrib/templates/orderCanceled.html
{% extends 'base.html' %}

{% block 'main' %}

<div class="row">
    <div class="container col-sm-12 col-md-12 col-lg-12">
        <div class="alert alert-danger">
            <strong>Danger!</strong> <p>You want to cancel the order?</p>
            <div>
                <a href="{% url 'toolcrib:orderssupervisorcart' order.pk %}" class="btn btn-success">Return</a>
            </div>
            <br>
            <div>
            <form action="." method="post">
                <div>
                    <input class="form-control" type="text" name="comments" style="width: 70%;" placeholder="Comments" >
                </div>
            </div>
            <br>
                {% csrf_token %}
                <button class="btn btn-danger" >Reject</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

toolcrib/templates/ordersmanager.html
{% extends 'base.html' %}

{% block 'main' %}

<!-- /BREADCRUMB -->
<div id="breadcrumb">
	<div class="container">
		<ul class="breadcrumb">
			<li><a href="{% url 'toolcrib:principal' %}">ToolCrib</a></li>
			<li class="active">Orders</li>
		</ul>
	</div>
</div><br>
<!-- /BREADCRUMB -->

<div class="box-body table-responsive no-padding">
	<table class="table table-hover">
		<tbody>
			<tr>
				<th>ID</th>
				<th>User</th>
				<th>Date</th>
				<th>N Items</th>
				<th>Urgency</th>
				<th>Status</th>
			</tr>
			{% for order in orders %}
			<tr>
				<td>				
					<a class="btn btn-primary" href="{% url 'toolcrib:ordersmanagercart' order.pk %}">{{order.id}}</a>
				</td>				
				<td>{{order.user }}</td>
				<td>{{order.date_order | date:"F /d/Y H:i" }}</td>
				<td>{{ order.order_detail_set.all.count}}</td>
				<td><span class="label label-success">{{order.get_level_display}}</span></td>
				<td><span class="label label-success">{{order.get_status_display}}</span></td>                  
			</tr>
		</tbody>
		{% empty %}
		<tr class="col-xs-12 col-sm-6 col-md-4 col-ls-4">
			<p>No orders pending</p>
		</tr>
		{% endfor %}
	</table>
</div>
<script>setTimeout('document.location.reload()', 9000); </script>
{% endblock %}

toolcrib/templates/orderssupervisor.html
{% extends 'base.html' %}

{% block 'main' %}

<!-- /BREADCRUMB -->
<div id="breadcrumb">
	<div class="container">
		<ul class="breadcrumb">
			<li><a href="{% url 'toolcrib:principal' %}">ToolCrib</a></li>
			<li class="active">Orders</li>
		</ul>
	</div>
</div><br>
<!-- /BREADCRUMB -->

<div class="box-body table-responsive no-padding">
	<table class="table table-hover">
		<tbody>
			<tr>
				<th>ID</th>
				<th>User</th>
				<th>Date</th>
				<th>N Items</th>
				<th>Urgency</th>
				<th>Status</th>
			</tr>
			{% for order in orders %}
			<tr>
				<td>				
					<a class="btn btn-primary" href="{% url 'toolcrib:orderssupervisorcart' order.pk %}">{{order.id}}</a>
				</td>				
				<td>{{order.user }}</td>
				<td>{{order.date_order | date:"F /d/Y H:i" }}</td>
				<td>{{ order.order_detail_set.all.count}}</td>
				<td><span 
					{% if order.level == '1'%}
						class="label label-success"
						{% elif order.level == '2' %}
						class="label label-warning"
						{% else %}
						class="label label-danger"
					{% endif %}
						>{{order.get_level_display}}</span></td>                  
				<td><span 
					{% if order.status == '1'%}
						class="label label-default"
						{% elif order.status == '2' %}
						class="label label-primary"
						{% elif order.status == '3' %}
						class="label label-danger"
						{% else %}
						class="label label-success"
					{% endif %}
						>{{order.get_status_display}}</span></td>                  
			</tr>
		</tbody>
		{% empty %}
		<tr class="col-xs-12 col-sm-6 col-md-4 col-ls-4">
			<p>No orders pending</p>
		</tr>
		{% endfor %}
	</table>
</div>
<script>setTimeout('document.location.reload()', 9000); </script>
{% endblock %}

toolcrib/templates/update_order_status_by_email.html
{% extends 'base.html' %}
{% load humanize %}


<!-- page not use. -->
{% block 'main' %}

<div class="row">
	<div class="col-sm-12 col-md-12 col-lg-12">
		<div class="alert alert-success">
  			<strong>Success!</strong> <p>Order {{order.id}} Approved succesfully</p>
  			<a href="{% url 'toolcrib:principal' %}" class="btn btn-success">Continue to the principal page</a>
		</div>
	</div>
</div>
{% endblock %}

toolcrib/templates/updateproduct.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block 'main' %}

<!-- /BREADCRUMB -->
<div id="breadcrumb">
	<div class="container">
		<ul class="breadcrumb">
			<li><a href="{% url 'toolcrib:principal' %}">ToolCrib</a></li>
			<li class="active">Update Tool</li>
		</ul>
	</div>
</div><br>
<!-- /BREADCRUMB -->

<form class="form" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{% bootstrap_form form %}
	<button class="btn btn-lg btn-primary btn-block" type="submit">Update</button>                
</form>

{% endblock %}